name: Build and Deploy

on:
  push:
    branches: 
      - main

jobs:
  buildAndDeploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Build docker images
        working-directory: .
        run: |
          docker compose build
      
      - name: Tag docker images
        run: |
          docker tag backend_todo:latest anuragkarumuri/githubactions:backend-${{github.run_number}}
          docker tag frontend_todo:latest anuragkarumuri/githubactions:frontend-${{github.run_number}}
      
      - name: Login to docker hub
        uses: docker/login-action@v1
        with: 
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}
      
      - name: Push Docker Images to Docker Hub
        run: |
          docker push anuragkarumuri/githubactions:backend-${{github.run_number}}
          docker push anuragkarumuri/githubactions:frontend-${{github.run_number}}
